#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DineWithaDane.Android.Resource", IsApplication=true)]

namespace DineWithaDane.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_navigation_drawer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int AddressEditor = 2131034122;
			
			// aapt resource value: 0x7f050019
			public const int AgeView = 2131034137;
			
			// aapt resource value: 0x7f050008
			public const int CancelButton = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int CancelDeletionBtn = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int DescriptionEditor = 2131034119;
			
			// aapt resource value: 0x7f05001b
			public const int EditProfileButton = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int InfoView = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int InnerRelativeLayout = 2131034146;
			
			// aapt resource value: 0x7f050006
			public const int NameEditor = 2131034118;
			
			// aapt resource value: 0x7f050018
			public const int NameView = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int ProfileDataLayout = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int ProfileLayout = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int ProfilePictureView = 2131034135;
			
			// aapt resource value: 0x7f050009
			public const int SaveButton = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int buttonLogin = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int buttonMenu = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int buttonSignUp = 2131034132;
			
			// aapt resource value: 0x7f050029
			public const int buttonSubmit = 2131034153;
			
			// aapt resource value: 0x7f050023
			public const int cancelReviewButton = 2131034147;
			
			// aapt resource value: 0x7f050001
			public const int content_frame = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int deleteAccountBtn = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int drawer_layout = 2131034112;
			
			// aapt resource value: 0x7f050028
			public const int editConfirm = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int editName = 2131034150;
			
			// aapt resource value: 0x7f050012
			public const int editPassword = 2131034130;
			
			// aapt resource value: 0x7f050005
			public const int editText1 = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int editUsername = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int frameLayout1 = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int layoutMain = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int left_drawer = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout1 = 2131034124;
			
			// aapt resource value: 0x7f050024
			public const int postReviewButton = 2131034148;
			
			// aapt resource value: 0x7f05002a
			public const int progressSignUp = 2131034154;
			
			// aapt resource value: 0x7f05001f
			public const int ratingbar = 2131034143;
			
			// aapt resource value: 0x7f05001c
			public const int reviewTitle = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int reviewUserInput = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int textConfirm = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int textName = 2131034149;
			
			// aapt resource value: 0x7f050011
			public const int textPassword = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int textUsername = 2131034127;
			
			// aapt resource value: 0x7f05001e
			public const int textView1 = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int textView2 = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int underscore = 2131034141;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int deletionDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditInfo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditText = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HeaderLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item_menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Profile = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int review_layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SignUp = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SpinnerItem = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int close_drawer = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int open_drawer = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
