language: csharp
solution: Solitude.sln

install:
  - nuget restore Solitude.sln

script:
  - cp Solitude.Server/App.config.sample Solitude.Server/App.config
  - xbuild /p:Configuration=Release Solitude.sln

notifications:
  email: false
